// Generated by AshTypescript - Shared Types
// Do not edit this file manually



export type Time = string;
export type UUID = string;
export type UtcDateTimeUsec = string;

// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email";
  id: UUID;
  email: string;
};



export type UserAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email";
  id: UUID;
  email: string;
};


// Game Schema
export type GameResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "description" | "status" | "isOwner";
  id: UUID;
  title: string;
  description: string | null;
  status: "active" | "paused" | "cancelled" | "completed";
  isOwner: boolean | null;
};



export type GameAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "description" | "status";
  id: UUID;
  title: string;
  description: string | null;
  status: "active" | "paused" | "cancelled" | "completed";
};


// Invitation Schema
export type InvitationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "characterName" | "characterSummary" | "status" | "expiresAt";
  id: UUID;
  email: string;
  characterName: string;
  characterSummary: string | null;
  status: "pending" | "accepted" | "declined" | "revoked";
  expiresAt: UtcDateTimeUsec;
};



export type InvitationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "characterName" | "characterSummary" | "status" | "expiresAt";
  id: UUID;
  email: string;
  characterName: string;
  characterSummary: string | null;
  status: "pending" | "accepted" | "declined" | "revoked";
  expiresAt: UtcDateTimeUsec;
};


// Player Schema
export type PlayerResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "characterName" | "characterSummary" | "status" | "visibleGmNotes";
  id: UUID;
  characterName: string;
  characterSummary: string | null;
  status: "active" | "inactive" | "done";
  visibleGmNotes: string | null;
};



export type PlayerAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "characterName" | "characterSummary" | "status";
  id: UUID;
  characterName: string;
  characterSummary: string | null;
  status: "active" | "inactive" | "done";
};


// Notification Schema
export type NotificationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "kind" | "subjectType" | "subjectId" | "readAt" | "resolvedAt" | "insertedAt" | "updatedAt";
  id: UUID;
  kind: "game_invitation" | "schedule_ready_for_availability" | "schedule_posted" | "schedule_updated" | "schedule_reminder";
  subjectType: string;
  subjectId: UUID;
  readAt: UtcDateTimeUsec | null;
  resolvedAt: UtcDateTimeUsec | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type NotificationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "kind" | "subjectType" | "subjectId" | "readAt" | "resolvedAt" | "insertedAt" | "updatedAt";
  id: UUID;
  kind: "game_invitation" | "schedule_ready_for_availability" | "schedule_posted" | "schedule_updated" | "schedule_reminder";
  subjectType: string;
  subjectId: UUID;
  readAt: UtcDateTimeUsec | null;
  resolvedAt: UtcDateTimeUsec | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// ParticipantDay Schema
export type ParticipantDayResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "day" | "status" | "insertedAt" | "updatedAt";
  id: UUID;
  day: number;
  status: "NA" | "I" | "A" | "IF" | "NP";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type ParticipantDayAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "day" | "status" | "insertedAt" | "updatedAt";
  id: UUID;
  day: number;
  status: "NA" | "I" | "A" | "IF" | "NP";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Schedule Schema
export type ScheduleResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "month" | "year" | "startTime" | "endTime" | "timeZone" | "status" | "postedAt" | "insertedAt" | "updatedAt" | "name";
  id: UUID;
  month: number;
  year: number;
  startTime: Time;
  endTime: Time;
  timeZone: string;
  status: "preparing" | "ready_for_availability" | "posted";
  postedAt: UtcDateTimeUsec | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  name: string | null;
};



export type ScheduleAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "month" | "year" | "startTime" | "endTime" | "timeZone" | "status" | "postedAt" | "insertedAt" | "updatedAt";
  id: UUID;
  month: number;
  year: number;
  startTime: Time;
  endTime: Time;
  timeZone: string;
  status: "preparing" | "ready_for_availability" | "posted";
  postedAt: UtcDateTimeUsec | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// ScheduleDay Schema
export type ScheduleDayResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "day" | "gmStatus" | "finalStatus" | "insertedAt" | "updatedAt";
  id: UUID;
  day: number;
  gmStatus: "NA" | "I" | "A" | "IF";
  finalStatus: "NA" | "A" | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type ScheduleDayAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "day" | "gmStatus" | "finalStatus" | "insertedAt" | "updatedAt";
  id: UUID;
  day: number;
  gmStatus: "NA" | "I" | "A" | "IF";
  finalStatus: "NA" | "A" | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// ScheduleParticipant Schema
export type ScheduleParticipantResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "isLateJoin" | "npOnly" | "submittedAt" | "joinedAt" | "insertedAt" | "updatedAt";
  id: UUID;
  isLateJoin: boolean;
  npOnly: boolean;
  submittedAt: UtcDateTimeUsec | null;
  joinedAt: UtcDateTimeUsec;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type ScheduleParticipantAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "isLateJoin" | "npOnly" | "submittedAt" | "joinedAt" | "insertedAt" | "updatedAt";
  id: UUID;
  isLateJoin: boolean;
  npOnly: boolean;
  submittedAt: UtcDateTimeUsec | null;
  joinedAt: UtcDateTimeUsec;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type GameFilterInput = {
  and?: Array<GameFilterInput>;
  or?: Array<GameFilterInput>;
  not?: Array<GameFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  status?: {
    eq?: "active" | "paused" | "cancelled" | "completed";
    notEq?: "active" | "paused" | "cancelled" | "completed";
    in?: Array<"active" | "paused" | "cancelled" | "completed">;
  };

  isOwner?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };



};
export type InvitationFilterInput = {
  and?: Array<InvitationFilterInput>;
  or?: Array<InvitationFilterInput>;
  not?: Array<InvitationFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  characterName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  characterSummary?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  status?: {
    eq?: "pending" | "accepted" | "declined" | "revoked";
    notEq?: "pending" | "accepted" | "declined" | "revoked";
    in?: Array<"pending" | "accepted" | "declined" | "revoked">;
  };

  expiresAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type PlayerFilterInput = {
  and?: Array<PlayerFilterInput>;
  or?: Array<PlayerFilterInput>;
  not?: Array<PlayerFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  characterName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  characterSummary?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  status?: {
    eq?: "active" | "inactive" | "done";
    notEq?: "active" | "inactive" | "done";
    in?: Array<"active" | "inactive" | "done">;
  };

  visibleGmNotes?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };



};
export type NotificationFilterInput = {
  and?: Array<NotificationFilterInput>;
  or?: Array<NotificationFilterInput>;
  not?: Array<NotificationFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  kind?: {
    eq?: "game_invitation" | "schedule_ready_for_availability" | "schedule_posted" | "schedule_updated" | "schedule_reminder";
    notEq?: "game_invitation" | "schedule_ready_for_availability" | "schedule_posted" | "schedule_updated" | "schedule_reminder";
    in?: Array<"game_invitation" | "schedule_ready_for_availability" | "schedule_posted" | "schedule_updated" | "schedule_reminder">;
  };

  subjectType?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  subjectId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  readAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  resolvedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type ParticipantDayFilterInput = {
  and?: Array<ParticipantDayFilterInput>;
  or?: Array<ParticipantDayFilterInput>;
  not?: Array<ParticipantDayFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  day?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  status?: {
    eq?: "NA" | "I" | "A" | "IF" | "NP";
    notEq?: "NA" | "I" | "A" | "IF" | "NP";
    in?: Array<"NA" | "I" | "A" | "IF" | "NP">;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type ScheduleFilterInput = {
  and?: Array<ScheduleFilterInput>;
  or?: Array<ScheduleFilterInput>;
  not?: Array<ScheduleFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  month?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  year?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  startTime?: {
    eq?: Time;
    notEq?: Time;
    in?: Array<Time>;
  };

  endTime?: {
    eq?: Time;
    notEq?: Time;
    in?: Array<Time>;
  };

  timeZone?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  status?: {
    eq?: "preparing" | "ready_for_availability" | "posted";
    notEq?: "preparing" | "ready_for_availability" | "posted";
    in?: Array<"preparing" | "ready_for_availability" | "posted">;
  };

  postedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };



};
export type ScheduleDayFilterInput = {
  and?: Array<ScheduleDayFilterInput>;
  or?: Array<ScheduleDayFilterInput>;
  not?: Array<ScheduleDayFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  day?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  gmStatus?: {
    eq?: "NA" | "I" | "A" | "IF";
    notEq?: "NA" | "I" | "A" | "IF";
    in?: Array<"NA" | "I" | "A" | "IF">;
  };

  finalStatus?: {
    eq?: "NA" | "A";
    notEq?: "NA" | "A";
    in?: Array<"NA" | "A">;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type ScheduleParticipantFilterInput = {
  and?: Array<ScheduleParticipantFilterInput>;
  or?: Array<ScheduleParticipantFilterInput>;
  not?: Array<ScheduleParticipantFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  isLateJoin?: {
    eq?: boolean;
    notEq?: boolean;
  };

  npOnly?: {
    eq?: boolean;
    notEq?: boolean;
  };

  submittedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  joinedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};


export const userFilterFields = ["id", "email"] as const;
export type UserFilterField = (typeof userFilterFields)[number];

export const gameFilterFields = ["id", "title", "description", "status", "isOwner"] as const;
export type GameFilterField = (typeof gameFilterFields)[number];

export const invitationFilterFields = ["id", "email", "characterName", "characterSummary", "status", "expiresAt"] as const;
export type InvitationFilterField = (typeof invitationFilterFields)[number];

export const playerFilterFields = ["id", "characterName", "characterSummary", "status", "visibleGmNotes"] as const;
export type PlayerFilterField = (typeof playerFilterFields)[number];

export const notificationFilterFields = ["id", "kind", "subjectType", "subjectId", "readAt", "resolvedAt", "insertedAt", "updatedAt"] as const;
export type NotificationFilterField = (typeof notificationFilterFields)[number];

export const participantDayFilterFields = ["id", "day", "status", "insertedAt", "updatedAt"] as const;
export type ParticipantDayFilterField = (typeof participantDayFilterFields)[number];

export const scheduleFilterFields = ["id", "month", "year", "startTime", "endTime", "timeZone", "status", "postedAt", "insertedAt", "updatedAt", "name"] as const;
export type ScheduleFilterField = (typeof scheduleFilterFields)[number];

export const scheduleDayFilterFields = ["id", "day", "gmStatus", "finalStatus", "insertedAt", "updatedAt"] as const;
export type ScheduleDayFilterField = (typeof scheduleDayFilterFields)[number];

export const scheduleParticipantFilterFields = ["id", "isLateJoin", "npOnly", "submittedAt", "joinedAt", "insertedAt", "updatedAt"] as const;
export type ScheduleParticipantFilterField = (typeof scheduleParticipantFilterFields)[number];


export const userSortFields = ["id", "email"] as const;
export type UserSortField = (typeof userSortFields)[number];

export const gameSortFields = ["id", "title", "description", "status", "isOwner"] as const;
export type GameSortField = (typeof gameSortFields)[number];

export const invitationSortFields = ["id", "email", "characterName", "characterSummary", "status", "expiresAt"] as const;
export type InvitationSortField = (typeof invitationSortFields)[number];

export const playerSortFields = ["id", "characterName", "characterSummary", "status", "visibleGmNotes"] as const;
export type PlayerSortField = (typeof playerSortFields)[number];

export const notificationSortFields = ["id", "kind", "subjectType", "subjectId", "readAt", "resolvedAt", "insertedAt", "updatedAt"] as const;
export type NotificationSortField = (typeof notificationSortFields)[number];

export const participantDaySortFields = ["id", "day", "status", "insertedAt", "updatedAt"] as const;
export type ParticipantDaySortField = (typeof participantDaySortFields)[number];

export const scheduleSortFields = ["id", "month", "year", "startTime", "endTime", "timeZone", "status", "postedAt", "insertedAt", "updatedAt", "name"] as const;
export type ScheduleSortField = (typeof scheduleSortFields)[number];

export const scheduleDaySortFields = ["id", "day", "gmStatus", "finalStatus", "insertedAt", "updatedAt"] as const;
export type ScheduleDaySortField = (typeof scheduleDaySortFields)[number];

export const scheduleParticipantSortFields = ["id", "isLateJoin", "npOnly", "submittedAt", "joinedAt", "insertedAt", "updatedAt"] as const;
export type ScheduleParticipantSortField = (typeof scheduleParticipantSortFields)[number];


// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };




