// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, GameFilterInput, GameResourceSchema, GameSortField, InferResult, SortString, UUID, UnifiedFieldSelection, UserResourceSchema, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type ReadCurrentUserFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferReadCurrentUserResult<
  Fields extends ReadCurrentUserFields,
> = InferResult<UserResourceSchema, Fields>;

export type ReadCurrentUserResult<Fields extends ReadCurrentUserFields> = | { success: true; data: InferReadCurrentUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function readCurrentUser<Fields extends ReadCurrentUserFields>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ReadCurrentUserResult<Fields>> {
  const payload = {
    action: "read_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ReadCurrentUserResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateReadCurrentUser(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "read_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetMineInput = {
  id: UUID;
};

export type GetMineFields = UnifiedFieldSelection<GameResourceSchema>[];
export type InferGetMineResult<
  Fields extends GetMineFields,
> = InferResult<GameResourceSchema, Fields>;

export type GetMineResult<Fields extends GetMineFields> = | { success: true; data: InferGetMineResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Game records
 *
 * @ashActionType :read
 */
export async function getMine<Fields extends GetMineFields>(
  config: {
  tenant?: string;
  input: GetMineInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMineResult<Fields>> {
  const payload = {
    action: "get_mine",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetMineResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Game records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMine(
  config: {
  tenant?: string;
  input: GetMineInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_mine",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMineActiveFields = UnifiedFieldSelection<GameResourceSchema>[];
export type InferListMineActiveResult<
  Fields extends ListMineActiveFields,
> = Array<InferResult<GameResourceSchema, Fields>>;

export type ListMineActiveResult<Fields extends ListMineActiveFields> = | { success: true; data: InferListMineActiveResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Game records
 *
 * @ashActionType :read
 */
export async function listMineActive<Fields extends ListMineActiveFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: GameFilterInput;
  sort?: SortString<GameSortField> | SortString<GameSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListMineActiveResult<Fields>> {
  const payload = {
    action: "list_mine_active",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListMineActiveResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Game records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMineActive(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_mine_active",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RegisterGameInput = {
  title: string;
  description?: string | null;
  status?: "active" | "paused" | "cancelled" | "completed";
};

export type RegisterGameFields = UnifiedFieldSelection<GameResourceSchema>[];

export type InferRegisterGameResult<
  Fields extends RegisterGameFields | undefined,
> = InferResult<GameResourceSchema, Fields>;

export type RegisterGameResult<Fields extends RegisterGameFields | undefined = undefined> = | { success: true; data: InferRegisterGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Game
 *
 * @ashActionType :create
 */
export async function registerGame<Fields extends RegisterGameFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RegisterGameInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RegisterGameResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "register_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RegisterGameResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Game
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateRegisterGame(
  config: {
  tenant?: string;
  input: RegisterGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "register_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateGameInput = {
  title?: string;
  description?: string | null;
  status?: "active" | "paused" | "cancelled" | "completed";
};

export type UpdateGameFields = UnifiedFieldSelection<GameResourceSchema>[];

export type InferUpdateGameResult<
  Fields extends UpdateGameFields | undefined,
> = InferResult<GameResourceSchema, Fields>;

export type UpdateGameResult<Fields extends UpdateGameFields | undefined = undefined> = | { success: true; data: InferUpdateGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Game
 *
 * @ashActionType :update
 */
export async function updateGame<Fields extends UpdateGameFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateGameInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateGameResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateGameResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Game
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateGame(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

