// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, GameFilterInput, GameResourceSchema, GameSortField, InferResult, InvitationFilterInput, InvitationResourceSchema, InvitationSortField, NotificationFilterInput, NotificationResourceSchema, NotificationSortField, PlayerFilterInput, PlayerResourceSchema, PlayerSortField, ScheduleFilterInput, ScheduleResourceSchema, ScheduleSortField, SortString, Time, UUID, UnifiedFieldSelection, UserResourceSchema, UtcDateTimeUsec, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type ReadCurrentUserFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferReadCurrentUserResult<
  Fields extends ReadCurrentUserFields,
> = InferResult<UserResourceSchema, Fields>;

export type ReadCurrentUserResult<Fields extends ReadCurrentUserFields> = | { success: true; data: InferReadCurrentUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function readCurrentUser<Fields extends ReadCurrentUserFields>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ReadCurrentUserResult<Fields>> {
  const payload = {
    action: "read_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ReadCurrentUserResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateReadCurrentUser(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "read_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DestroyGameResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Game
 *
 * @ashActionType :destroy
 */
export async function destroyGame(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyGameResult> {
  const payload = {
    action: "destroy_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyGameResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Game
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyGame(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetMineInput = {
  id: UUID;
};

export type GetMineFields = UnifiedFieldSelection<GameResourceSchema>[];
export type InferGetMineResult<
  Fields extends GetMineFields,
> = InferResult<GameResourceSchema, Fields>;

export type GetMineResult<Fields extends GetMineFields> = | { success: true; data: InferGetMineResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Game records
 *
 * @ashActionType :read
 */
export async function getMine<Fields extends GetMineFields>(
  config: {
  tenant?: string;
  input: GetMineInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMineResult<Fields>> {
  const payload = {
    action: "get_mine",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetMineResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Game records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMine(
  config: {
  tenant?: string;
  input: GetMineInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_mine",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMineFields = UnifiedFieldSelection<GameResourceSchema>[];
export type InferListMineResult<
  Fields extends ListMineFields,
> = Array<InferResult<GameResourceSchema, Fields>>;

export type ListMineResult<Fields extends ListMineFields> = | { success: true; data: InferListMineResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Game records
 *
 * @ashActionType :read
 */
export async function listMine<Fields extends ListMineFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: GameFilterInput;
  sort?: SortString<GameSortField> | SortString<GameSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListMineResult<Fields>> {
  const payload = {
    action: "list_mine",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListMineResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Game records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMine(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_mine",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMineActiveFields = UnifiedFieldSelection<GameResourceSchema>[];
export type InferListMineActiveResult<
  Fields extends ListMineActiveFields,
> = Array<InferResult<GameResourceSchema, Fields>>;

export type ListMineActiveResult<Fields extends ListMineActiveFields> = | { success: true; data: InferListMineActiveResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Game records
 *
 * @ashActionType :read
 */
export async function listMineActive<Fields extends ListMineActiveFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: GameFilterInput;
  sort?: SortString<GameSortField> | SortString<GameSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListMineActiveResult<Fields>> {
  const payload = {
    action: "list_mine_active",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListMineActiveResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Game records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMineActive(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_mine_active",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RegisterGameInput = {
  title: string;
  description?: string | null;
  status?: "active" | "paused" | "cancelled" | "completed";
};

export type RegisterGameFields = UnifiedFieldSelection<GameResourceSchema>[];

export type InferRegisterGameResult<
  Fields extends RegisterGameFields | undefined,
> = InferResult<GameResourceSchema, Fields>;

export type RegisterGameResult<Fields extends RegisterGameFields | undefined = undefined> = | { success: true; data: InferRegisterGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Game
 *
 * @ashActionType :create
 */
export async function registerGame<Fields extends RegisterGameFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RegisterGameInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RegisterGameResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "register_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RegisterGameResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Game
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateRegisterGame(
  config: {
  tenant?: string;
  input: RegisterGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "register_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateGameInput = {
  title?: string;
  description?: string | null;
  status?: "active" | "paused" | "cancelled" | "completed";
};

export type UpdateGameFields = UnifiedFieldSelection<GameResourceSchema>[];

export type InferUpdateGameResult<
  Fields extends UpdateGameFields | undefined,
> = InferResult<GameResourceSchema, Fields>;

export type UpdateGameResult<Fields extends UpdateGameFields | undefined = undefined> = | { success: true; data: InferUpdateGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Game
 *
 * @ashActionType :update
 */
export async function updateGame<Fields extends UpdateGameFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateGameInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateGameResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateGameResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Game
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateGame(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type AcceptInvitationInput = {
  id: UUID;
  token: string;
};

export type AcceptInvitationFields = UnifiedFieldSelection<{id: UUID, status: string, acceptedPlayerId: UUID | null, __type: "TypedMap", __primitiveFields: "id" | "status" | "acceptedPlayerId"}>[];

export type InferAcceptInvitationResult<
  Fields extends AcceptInvitationFields | undefined,
> = InferResult<{id: UUID, status: string, acceptedPlayerId: UUID | null, __type: "TypedMap", __primitiveFields: "id" | "status" | "acceptedPlayerId"}, Fields>;

export type AcceptInvitationResult<Fields extends AcceptInvitationFields | undefined = undefined> = | { success: true; data: InferAcceptInvitationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Invitation
 *
 * @ashActionType :action
 */
export async function acceptInvitation<Fields extends AcceptInvitationFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: AcceptInvitationInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<AcceptInvitationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "accept_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<AcceptInvitationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Invitation
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateAcceptInvitation(
  config: {
  tenant?: string;
  input: AcceptInvitationInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "accept_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type AcceptInvitationForMeFields = UnifiedFieldSelection<InvitationResourceSchema>[];

export type InferAcceptInvitationForMeResult<
  Fields extends AcceptInvitationForMeFields | undefined,
> = InferResult<InvitationResourceSchema, Fields>;

export type AcceptInvitationForMeResult<Fields extends AcceptInvitationForMeFields | undefined = undefined> = | { success: true; data: InferAcceptInvitationForMeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Invitation
 *
 * @ashActionType :update
 */
export async function acceptInvitationForMe<Fields extends AcceptInvitationForMeFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<AcceptInvitationForMeResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "accept_invitation_for_me",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<AcceptInvitationForMeResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Invitation
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateAcceptInvitationForMe(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "accept_invitation_for_me",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateInvitationInput = {
  characterName: string;
  characterSummary?: string | null;
  gmNotes?: string | null;
  email: string;
  gameId: UUID;
};

export type CreateInvitationFields = UnifiedFieldSelection<InvitationResourceSchema>[];

export type InferCreateInvitationResult<
  Fields extends CreateInvitationFields | undefined,
> = InferResult<InvitationResourceSchema, Fields>;

export type CreateInvitationResult<Fields extends CreateInvitationFields | undefined = undefined> = | { success: true; data: InferCreateInvitationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Invitation
 *
 * @ashActionType :create
 */
export async function createInvitation<Fields extends CreateInvitationFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateInvitationInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateInvitationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateInvitationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Invitation
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateInvitation(
  config: {
  tenant?: string;
  input: CreateInvitationInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DeclineInvitationInput = {
  id: UUID;
  token: string;
};

export type DeclineInvitationFields = UnifiedFieldSelection<{id: UUID, status: string, __type: "TypedMap", __primitiveFields: "id" | "status"}>[];

export type InferDeclineInvitationResult<
  Fields extends DeclineInvitationFields | undefined,
> = InferResult<{id: UUID, status: string, __type: "TypedMap", __primitiveFields: "id" | "status"}, Fields>;

export type DeclineInvitationResult<Fields extends DeclineInvitationFields | undefined = undefined> = | { success: true; data: InferDeclineInvitationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Invitation
 *
 * @ashActionType :action
 */
export async function declineInvitation<Fields extends DeclineInvitationFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: DeclineInvitationInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeclineInvitationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "decline_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<DeclineInvitationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Invitation
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateDeclineInvitation(
  config: {
  tenant?: string;
  input: DeclineInvitationInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "decline_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DeclineInvitationForMeFields = UnifiedFieldSelection<InvitationResourceSchema>[];

export type InferDeclineInvitationForMeResult<
  Fields extends DeclineInvitationForMeFields | undefined,
> = InferResult<InvitationResourceSchema, Fields>;

export type DeclineInvitationForMeResult<Fields extends DeclineInvitationForMeFields | undefined = undefined> = | { success: true; data: InferDeclineInvitationForMeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Invitation
 *
 * @ashActionType :update
 */
export async function declineInvitationForMe<Fields extends DeclineInvitationForMeFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeclineInvitationForMeResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "decline_invitation_for_me",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<DeclineInvitationForMeResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Invitation
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateDeclineInvitationForMe(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "decline_invitation_for_me",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMyPendingInvitationsFields = UnifiedFieldSelection<InvitationResourceSchema>[];
export type InferListMyPendingInvitationsResult<
  Fields extends ListMyPendingInvitationsFields,
> = Array<InferResult<InvitationResourceSchema, Fields>>;

export type ListMyPendingInvitationsResult<Fields extends ListMyPendingInvitationsFields> = | { success: true; data: InferListMyPendingInvitationsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Invitation records
 *
 * @ashActionType :read
 */
export async function listMyPendingInvitations<Fields extends ListMyPendingInvitationsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: InvitationFilterInput;
  sort?: SortString<InvitationSortField> | SortString<InvitationSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListMyPendingInvitationsResult<Fields>> {
  const payload = {
    action: "list_my_pending_invitations",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListMyPendingInvitationsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Invitation records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMyPendingInvitations(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_my_pending_invitations",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListPendingInvitationsForGameInput = {
  gameId: UUID;
};

export type ListPendingInvitationsForGameFields = UnifiedFieldSelection<InvitationResourceSchema>[];
export type InferListPendingInvitationsForGameResult<
  Fields extends ListPendingInvitationsForGameFields,
> = Array<InferResult<InvitationResourceSchema, Fields>>;

export type ListPendingInvitationsForGameResult<Fields extends ListPendingInvitationsForGameFields> = | { success: true; data: InferListPendingInvitationsForGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Invitation records
 *
 * @ashActionType :read
 */
export async function listPendingInvitationsForGame<Fields extends ListPendingInvitationsForGameFields>(
  config: {
  tenant?: string;
  input: ListPendingInvitationsForGameInput;
  fields: Fields;
  filter?: InvitationFilterInput;
  sort?: SortString<InvitationSortField> | SortString<InvitationSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListPendingInvitationsForGameResult<Fields>> {
  const payload = {
    action: "list_pending_invitations_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListPendingInvitationsForGameResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Invitation records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListPendingInvitationsForGame(
  config: {
  tenant?: string;
  input: ListPendingInvitationsForGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_pending_invitations_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type PreviewInvitationInput = {
  token: string;
};

export type PreviewInvitationFields = UnifiedFieldSelection<{id: UUID, gameTitle: string, inviterEmail: string, characterName: string, expiresAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "id" | "gameTitle" | "inviterEmail" | "characterName" | "expiresAt"}>[];

export type InferPreviewInvitationResult<
  Fields extends PreviewInvitationFields | undefined,
> = InferResult<{id: UUID, gameTitle: string, inviterEmail: string, characterName: string, expiresAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "id" | "gameTitle" | "inviterEmail" | "characterName" | "expiresAt"}, Fields>;

export type PreviewInvitationResult<Fields extends PreviewInvitationFields | undefined = undefined> = | { success: true; data: InferPreviewInvitationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Invitation
 *
 * @ashActionType :action
 */
export async function previewInvitation<Fields extends PreviewInvitationFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: PreviewInvitationInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<PreviewInvitationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "preview_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<PreviewInvitationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Invitation
 *
 * @ashActionType :action
 * @validation true
 */
export async function validatePreviewInvitation(
  config: {
  tenant?: string;
  input: PreviewInvitationInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "preview_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RevokeInvitationFields = UnifiedFieldSelection<InvitationResourceSchema>[];

export type InferRevokeInvitationResult<
  Fields extends RevokeInvitationFields | undefined,
> = InferResult<InvitationResourceSchema, Fields>;

export type RevokeInvitationResult<Fields extends RevokeInvitationFields | undefined = undefined> = | { success: true; data: InferRevokeInvitationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Invitation
 *
 * @ashActionType :update
 */
export async function revokeInvitation<Fields extends RevokeInvitationFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RevokeInvitationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "revoke_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RevokeInvitationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Invitation
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRevokeInvitation(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "revoke_invitation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMyCharactersFields = UnifiedFieldSelection<PlayerResourceSchema>[];
export type InferListMyCharactersResult<
  Fields extends ListMyCharactersFields,
> = Array<InferResult<PlayerResourceSchema, Fields>>;

export type ListMyCharactersResult<Fields extends ListMyCharactersFields> = | { success: true; data: InferListMyCharactersResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Player records
 *
 * @ashActionType :read
 */
export async function listMyCharacters<Fields extends ListMyCharactersFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: PlayerFilterInput;
  sort?: SortString<PlayerSortField> | SortString<PlayerSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListMyCharactersResult<Fields>> {
  const payload = {
    action: "list_my_characters",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListMyCharactersResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Player records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMyCharacters(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_my_characters",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListPlayersForGameInput = {
  gameId: UUID;
};

export type ListPlayersForGameFields = UnifiedFieldSelection<PlayerResourceSchema>[];
export type InferListPlayersForGameResult<
  Fields extends ListPlayersForGameFields,
> = Array<InferResult<PlayerResourceSchema, Fields>>;

export type ListPlayersForGameResult<Fields extends ListPlayersForGameFields> = | { success: true; data: InferListPlayersForGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Player records
 *
 * @ashActionType :read
 */
export async function listPlayersForGame<Fields extends ListPlayersForGameFields>(
  config: {
  tenant?: string;
  input: ListPlayersForGameInput;
  fields: Fields;
  filter?: PlayerFilterInput;
  sort?: SortString<PlayerSortField> | SortString<PlayerSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListPlayersForGameResult<Fields>> {
  const payload = {
    action: "list_players_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListPlayersForGameResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Player records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListPlayersForGame(
  config: {
  tenant?: string;
  input: ListPlayersForGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_players_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListPlayersForGmInput = {
  gameId: UUID;
};

export type ListPlayersForGmFields = UnifiedFieldSelection<PlayerResourceSchema>[];
export type InferListPlayersForGmResult<
  Fields extends ListPlayersForGmFields,
> = Array<InferResult<PlayerResourceSchema, Fields>>;

export type ListPlayersForGmResult<Fields extends ListPlayersForGmFields> = | { success: true; data: InferListPlayersForGmResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Player records
 *
 * @ashActionType :read
 */
export async function listPlayersForGm<Fields extends ListPlayersForGmFields>(
  config: {
  tenant?: string;
  input: ListPlayersForGmInput;
  fields: Fields;
  filter?: PlayerFilterInput;
  sort?: SortString<PlayerSortField> | SortString<PlayerSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListPlayersForGmResult<Fields>> {
  const payload = {
    action: "list_players_for_gm",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListPlayersForGmResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Player records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListPlayersForGm(
  config: {
  tenant?: string;
  input: ListPlayersForGmInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_players_for_gm",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdatePlayerInput = {
  characterName?: string;
  characterSummary?: string | null;
  gmNotes?: string | null;
  status?: "active" | "inactive" | "done";
};

export type UpdatePlayerFields = UnifiedFieldSelection<PlayerResourceSchema>[];

export type InferUpdatePlayerResult<
  Fields extends UpdatePlayerFields | undefined,
> = InferResult<PlayerResourceSchema, Fields>;

export type UpdatePlayerResult<Fields extends UpdatePlayerFields | undefined = undefined> = | { success: true; data: InferUpdatePlayerResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Player
 *
 * @ashActionType :update
 */
export async function updatePlayer<Fields extends UpdatePlayerFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdatePlayerInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdatePlayerResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_player",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdatePlayerResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Player
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdatePlayer(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdatePlayerInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_player",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type InferCountMyUnreadResult = number;

export type CountMyUnreadResult = | { success: true; data: InferCountMyUnreadResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Notification
 *
 * @ashActionType :action
 */
export async function countMyUnread(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CountMyUnreadResult> {
  const payload = {
    action: "count_my_unread",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeActionRpcRequest<CountMyUnreadResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Notification
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateCountMyUnread(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "count_my_unread",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMyNotificationsFields = UnifiedFieldSelection<NotificationResourceSchema>[];
export type InferListMyNotificationsResult<
  Fields extends ListMyNotificationsFields,
> = Array<InferResult<NotificationResourceSchema, Fields>>;

export type ListMyNotificationsResult<Fields extends ListMyNotificationsFields> = | { success: true; data: InferListMyNotificationsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Notification records
 *
 * @ashActionType :read
 */
export async function listMyNotifications<Fields extends ListMyNotificationsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: NotificationFilterInput;
  sort?: SortString<NotificationSortField> | SortString<NotificationSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListMyNotificationsResult<Fields>> {
  const payload = {
    action: "list_my_notifications",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListMyNotificationsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Notification records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMyNotifications(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_my_notifications",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type MarkNotificationReadFields = UnifiedFieldSelection<NotificationResourceSchema>[];

export type InferMarkNotificationReadResult<
  Fields extends MarkNotificationReadFields | undefined,
> = InferResult<NotificationResourceSchema, Fields>;

export type MarkNotificationReadResult<Fields extends MarkNotificationReadFields | undefined = undefined> = | { success: true; data: InferMarkNotificationReadResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Notification
 *
 * @ashActionType :update
 */
export async function markNotificationRead<Fields extends MarkNotificationReadFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<MarkNotificationReadResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "mark_notification_read",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<MarkNotificationReadResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Notification
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateMarkNotificationRead(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "mark_notification_read",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetScheduleForGameInput = {
  id: UUID;
  gameId: UUID;
};

export type GetScheduleForGameFields = UnifiedFieldSelection<ScheduleResourceSchema>[];
export type InferGetScheduleForGameResult<
  Fields extends GetScheduleForGameFields,
> = InferResult<ScheduleResourceSchema, Fields>;

export type GetScheduleForGameResult<Fields extends GetScheduleForGameFields> = | { success: true; data: InferGetScheduleForGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Schedule records
 *
 * @ashActionType :read
 */
export async function getScheduleForGame<Fields extends GetScheduleForGameFields>(
  config: {
  tenant?: string;
  input: GetScheduleForGameInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetScheduleForGameResult<Fields>> {
  const payload = {
    action: "get_schedule_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetScheduleForGameResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Schedule records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetScheduleForGame(
  config: {
  tenant?: string;
  input: GetScheduleForGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_schedule_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type InitiateScheduleInput = {
  month: number;
  year: number;
  startTime: Time;
  endTime: Time;
  timeZone: string;
  gameId: UUID;
};

export type InitiateScheduleFields = UnifiedFieldSelection<ScheduleResourceSchema>[];

export type InferInitiateScheduleResult<
  Fields extends InitiateScheduleFields | undefined,
> = InferResult<ScheduleResourceSchema, Fields>;

export type InitiateScheduleResult<Fields extends InitiateScheduleFields | undefined = undefined> = | { success: true; data: InferInitiateScheduleResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Schedule
 *
 * @ashActionType :create
 */
export async function initiateSchedule<Fields extends InitiateScheduleFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: InitiateScheduleInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<InitiateScheduleResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "initiate_schedule",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<InitiateScheduleResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Schedule
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateInitiateSchedule(
  config: {
  tenant?: string;
  input: InitiateScheduleInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "initiate_schedule",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListSchedulesForGameInput = {
  gameId: UUID;
};

export type ListSchedulesForGameFields = UnifiedFieldSelection<ScheduleResourceSchema>[];
export type InferListSchedulesForGameResult<
  Fields extends ListSchedulesForGameFields,
> = Array<InferResult<ScheduleResourceSchema, Fields>>;

export type ListSchedulesForGameResult<Fields extends ListSchedulesForGameFields> = | { success: true; data: InferListSchedulesForGameResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Schedule records
 *
 * @ashActionType :read
 */
export async function listSchedulesForGame<Fields extends ListSchedulesForGameFields>(
  config: {
  tenant?: string;
  input: ListSchedulesForGameInput;
  fields: Fields;
  filter?: ScheduleFilterInput;
  sort?: SortString<ScheduleSortField> | SortString<ScheduleSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListSchedulesForGameResult<Fields>> {
  const payload = {
    action: "list_schedules_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListSchedulesForGameResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Schedule records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListSchedulesForGame(
  config: {
  tenant?: string;
  input: ListSchedulesForGameInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_schedules_for_game",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListSchedulesForGameTopSixInput = {
  gameId: UUID;
};

export type ListSchedulesForGameTopSixFields = UnifiedFieldSelection<ScheduleResourceSchema>[];
export type InferListSchedulesForGameTopSixResult<
  Fields extends ListSchedulesForGameTopSixFields,
> = Array<InferResult<ScheduleResourceSchema, Fields>>;

export type ListSchedulesForGameTopSixResult<Fields extends ListSchedulesForGameTopSixFields> = | { success: true; data: InferListSchedulesForGameTopSixResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Schedule records
 *
 * @ashActionType :read
 */
export async function listSchedulesForGameTopSix<Fields extends ListSchedulesForGameTopSixFields>(
  config: {
  tenant?: string;
  input: ListSchedulesForGameTopSixInput;
  fields: Fields;
  filter?: ScheduleFilterInput;
  sort?: SortString<ScheduleSortField> | SortString<ScheduleSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListSchedulesForGameTopSixResult<Fields>> {
  const payload = {
    action: "list_schedules_for_game_top_six",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListSchedulesForGameTopSixResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Schedule records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListSchedulesForGameTopSix(
  config: {
  tenant?: string;
  input: ListSchedulesForGameTopSixInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_schedules_for_game_top_six",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SetScheduleGmDayInput = {
  day: number;
  status: "NA" | "I" | "A" | "IF";
};

export type SetScheduleGmDayFields = UnifiedFieldSelection<ScheduleResourceSchema>[];

export type InferSetScheduleGmDayResult<
  Fields extends SetScheduleGmDayFields | undefined,
> = InferResult<ScheduleResourceSchema, Fields>;

export type SetScheduleGmDayResult<Fields extends SetScheduleGmDayFields | undefined = undefined> = | { success: true; data: InferSetScheduleGmDayResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Schedule
 *
 * @ashActionType :update
 */
export async function setScheduleGmDay<Fields extends SetScheduleGmDayFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: SetScheduleGmDayInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetScheduleGmDayResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_schedule_gm_day",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetScheduleGmDayResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Schedule
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateSetScheduleGmDay(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: SetScheduleGmDayInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_schedule_gm_day",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type TransitionScheduleToReadyFields = UnifiedFieldSelection<ScheduleResourceSchema>[];

export type InferTransitionScheduleToReadyResult<
  Fields extends TransitionScheduleToReadyFields | undefined,
> = InferResult<ScheduleResourceSchema, Fields>;

export type TransitionScheduleToReadyResult<Fields extends TransitionScheduleToReadyFields | undefined = undefined> = | { success: true; data: InferTransitionScheduleToReadyResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Schedule
 *
 * @ashActionType :update
 */
export async function transitionScheduleToReady<Fields extends TransitionScheduleToReadyFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<TransitionScheduleToReadyResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "transition_schedule_to_ready",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<TransitionScheduleToReadyResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Schedule
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateTransitionScheduleToReady(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "transition_schedule_to_ready",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

