/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsIndexRouteImport } from './routes/invitations.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as PasswordResetTokenRouteImport } from './routes/password-reset.$token'
import { Route as Magic_linkTokenRouteImport } from './routes/magic_link.$token'
import { Route as InvitationsTokenRouteImport } from './routes/invitations.$token'
import { Route as GamesNewRouteImport } from './routes/games.new'
import { Route as Confirm_new_userTokenRouteImport } from './routes/confirm_new_user.$token'
import { Route as GamesIdIndexRouteImport } from './routes/games.$id.index'
import { Route as CharactersIdIndexRouteImport } from './routes/characters.$id.index'
import { Route as GamesIdEditRouteImport } from './routes/games.$id.edit'
import { Route as GamesGameIdSchedulesIndexRouteImport } from './routes/games.$gameId.schedules.index'
import { Route as CharactersCharacterIdSchedulesIndexRouteImport } from './routes/characters.$characterId.schedules.index'
import { Route as GamesGameIdSchedulesScheduleIdRouteImport } from './routes/games.$gameId.schedules.$scheduleId'
import { Route as CharactersCharacterIdSchedulesScheduleIdRouteImport } from './routes/characters.$characterId.schedules.$scheduleId'
import { Route as GamesGameIdSchedulesScheduleIdSchedulingRouteImport } from './routes/games.$gameId.schedules.$scheduleId_.scheduling'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsIndexRoute = InvitationsIndexRouteImport.update({
  id: '/invitations/',
  path: '/invitations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetTokenRoute = PasswordResetTokenRouteImport.update({
  id: '/password-reset/$token',
  path: '/password-reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Magic_linkTokenRoute = Magic_linkTokenRouteImport.update({
  id: '/magic_link/$token',
  path: '/magic_link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const Confirm_new_userTokenRoute = Confirm_new_userTokenRouteImport.update({
  id: '/confirm_new_user/$token',
  path: '/confirm_new_user/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdIndexRoute = GamesIdIndexRouteImport.update({
  id: '/games/$id/',
  path: '/games/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdIndexRoute = CharactersIdIndexRouteImport.update({
  id: '/characters/$id/',
  path: '/characters/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdEditRoute = GamesIdEditRouteImport.update({
  id: '/games/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdSchedulesIndexRoute =
  GamesGameIdSchedulesIndexRouteImport.update({
    id: '/games/$gameId/schedules/',
    path: '/games/$gameId/schedules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CharactersCharacterIdSchedulesIndexRoute =
  CharactersCharacterIdSchedulesIndexRouteImport.update({
    id: '/characters/$characterId/schedules/',
    path: '/characters/$characterId/schedules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesGameIdSchedulesScheduleIdRoute =
  GamesGameIdSchedulesScheduleIdRouteImport.update({
    id: '/games/$gameId/schedules/$scheduleId',
    path: '/games/$gameId/schedules/$scheduleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CharactersCharacterIdSchedulesScheduleIdRoute =
  CharactersCharacterIdSchedulesScheduleIdRouteImport.update({
    id: '/characters/$characterId/schedules/$scheduleId',
    path: '/characters/$characterId/schedules/$scheduleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesGameIdSchedulesScheduleIdSchedulingRoute =
  GamesGameIdSchedulesScheduleIdSchedulingRouteImport.update({
    id: '/games/$gameId/schedules/$scheduleId_/scheduling',
    path: '/games/$gameId/schedules/$scheduleId/scheduling',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/magic-link': typeof MagicLinkRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/confirm_new_user/$token': typeof Confirm_new_userTokenRoute
  '/games/new': typeof GamesNewRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/magic_link/$token': typeof Magic_linkTokenRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/characters/': typeof CharactersIndexRoute
  '/games/': typeof GamesIndexRoute
  '/invitations/': typeof InvitationsIndexRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/characters/$id/': typeof CharactersIdIndexRoute
  '/games/$id/': typeof GamesIdIndexRoute
  '/characters/$characterId/schedules/$scheduleId': typeof CharactersCharacterIdSchedulesScheduleIdRoute
  '/games/$gameId/schedules/$scheduleId': typeof GamesGameIdSchedulesScheduleIdRoute
  '/characters/$characterId/schedules/': typeof CharactersCharacterIdSchedulesIndexRoute
  '/games/$gameId/schedules/': typeof GamesGameIdSchedulesIndexRoute
  '/games/$gameId/schedules/$scheduleId/scheduling': typeof GamesGameIdSchedulesScheduleIdSchedulingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/magic-link': typeof MagicLinkRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/confirm_new_user/$token': typeof Confirm_new_userTokenRoute
  '/games/new': typeof GamesNewRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/magic_link/$token': typeof Magic_linkTokenRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/characters': typeof CharactersIndexRoute
  '/games': typeof GamesIndexRoute
  '/invitations': typeof InvitationsIndexRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/characters/$id': typeof CharactersIdIndexRoute
  '/games/$id': typeof GamesIdIndexRoute
  '/characters/$characterId/schedules/$scheduleId': typeof CharactersCharacterIdSchedulesScheduleIdRoute
  '/games/$gameId/schedules/$scheduleId': typeof GamesGameIdSchedulesScheduleIdRoute
  '/characters/$characterId/schedules': typeof CharactersCharacterIdSchedulesIndexRoute
  '/games/$gameId/schedules': typeof GamesGameIdSchedulesIndexRoute
  '/games/$gameId/schedules/$scheduleId/scheduling': typeof GamesGameIdSchedulesScheduleIdSchedulingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/magic-link': typeof MagicLinkRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/confirm_new_user/$token': typeof Confirm_new_userTokenRoute
  '/games/new': typeof GamesNewRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/magic_link/$token': typeof Magic_linkTokenRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/characters/': typeof CharactersIndexRoute
  '/games/': typeof GamesIndexRoute
  '/invitations/': typeof InvitationsIndexRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/characters/$id/': typeof CharactersIdIndexRoute
  '/games/$id/': typeof GamesIdIndexRoute
  '/characters/$characterId/schedules/$scheduleId': typeof CharactersCharacterIdSchedulesScheduleIdRoute
  '/games/$gameId/schedules/$scheduleId': typeof GamesGameIdSchedulesScheduleIdRoute
  '/characters/$characterId/schedules/': typeof CharactersCharacterIdSchedulesIndexRoute
  '/games/$gameId/schedules/': typeof GamesGameIdSchedulesIndexRoute
  '/games/$gameId/schedules/$scheduleId_/scheduling': typeof GamesGameIdSchedulesScheduleIdSchedulingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/magic-link'
    | '/notifications'
    | '/register'
    | '/reset'
    | '/sign-in'
    | '/confirm_new_user/$token'
    | '/games/new'
    | '/invitations/$token'
    | '/magic_link/$token'
    | '/password-reset/$token'
    | '/characters/'
    | '/games/'
    | '/invitations/'
    | '/games/$id/edit'
    | '/characters/$id/'
    | '/games/$id/'
    | '/characters/$characterId/schedules/$scheduleId'
    | '/games/$gameId/schedules/$scheduleId'
    | '/characters/$characterId/schedules/'
    | '/games/$gameId/schedules/'
    | '/games/$gameId/schedules/$scheduleId/scheduling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/magic-link'
    | '/notifications'
    | '/register'
    | '/reset'
    | '/sign-in'
    | '/confirm_new_user/$token'
    | '/games/new'
    | '/invitations/$token'
    | '/magic_link/$token'
    | '/password-reset/$token'
    | '/characters'
    | '/games'
    | '/invitations'
    | '/games/$id/edit'
    | '/characters/$id'
    | '/games/$id'
    | '/characters/$characterId/schedules/$scheduleId'
    | '/games/$gameId/schedules/$scheduleId'
    | '/characters/$characterId/schedules'
    | '/games/$gameId/schedules'
    | '/games/$gameId/schedules/$scheduleId/scheduling'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/magic-link'
    | '/notifications'
    | '/register'
    | '/reset'
    | '/sign-in'
    | '/confirm_new_user/$token'
    | '/games/new'
    | '/invitations/$token'
    | '/magic_link/$token'
    | '/password-reset/$token'
    | '/characters/'
    | '/games/'
    | '/invitations/'
    | '/games/$id/edit'
    | '/characters/$id/'
    | '/games/$id/'
    | '/characters/$characterId/schedules/$scheduleId'
    | '/games/$gameId/schedules/$scheduleId'
    | '/characters/$characterId/schedules/'
    | '/games/$gameId/schedules/'
    | '/games/$gameId/schedules/$scheduleId_/scheduling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  MagicLinkRoute: typeof MagicLinkRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  SignInRoute: typeof SignInRoute
  Confirm_new_userTokenRoute: typeof Confirm_new_userTokenRoute
  GamesNewRoute: typeof GamesNewRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  Magic_linkTokenRoute: typeof Magic_linkTokenRoute
  PasswordResetTokenRoute: typeof PasswordResetTokenRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  InvitationsIndexRoute: typeof InvitationsIndexRoute
  GamesIdEditRoute: typeof GamesIdEditRoute
  CharactersIdIndexRoute: typeof CharactersIdIndexRoute
  GamesIdIndexRoute: typeof GamesIdIndexRoute
  CharactersCharacterIdSchedulesScheduleIdRoute: typeof CharactersCharacterIdSchedulesScheduleIdRoute
  GamesGameIdSchedulesScheduleIdRoute: typeof GamesGameIdSchedulesScheduleIdRoute
  CharactersCharacterIdSchedulesIndexRoute: typeof CharactersCharacterIdSchedulesIndexRoute
  GamesGameIdSchedulesIndexRoute: typeof GamesGameIdSchedulesIndexRoute
  GamesGameIdSchedulesScheduleIdSchedulingRoute: typeof GamesGameIdSchedulesScheduleIdSchedulingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/': {
      id: '/invitations/'
      path: '/invitations'
      fullPath: '/invitations/'
      preLoaderRoute: typeof InvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/$token': {
      id: '/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/password-reset/$token'
      preLoaderRoute: typeof PasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic_link/$token': {
      id: '/magic_link/$token'
      path: '/magic_link/$token'
      fullPath: '/magic_link/$token'
      preLoaderRoute: typeof Magic_linkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm_new_user/$token': {
      id: '/confirm_new_user/$token'
      path: '/confirm_new_user/$token'
      fullPath: '/confirm_new_user/$token'
      preLoaderRoute: typeof Confirm_new_userTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/': {
      id: '/games/$id/'
      path: '/games/$id'
      fullPath: '/games/$id/'
      preLoaderRoute: typeof GamesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id/': {
      id: '/characters/$id/'
      path: '/characters/$id'
      fullPath: '/characters/$id/'
      preLoaderRoute: typeof CharactersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/edit': {
      id: '/games/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof GamesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/schedules/': {
      id: '/games/$gameId/schedules/'
      path: '/games/$gameId/schedules'
      fullPath: '/games/$gameId/schedules/'
      preLoaderRoute: typeof GamesGameIdSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId/schedules/': {
      id: '/characters/$characterId/schedules/'
      path: '/characters/$characterId/schedules'
      fullPath: '/characters/$characterId/schedules/'
      preLoaderRoute: typeof CharactersCharacterIdSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/schedules/$scheduleId': {
      id: '/games/$gameId/schedules/$scheduleId'
      path: '/games/$gameId/schedules/$scheduleId'
      fullPath: '/games/$gameId/schedules/$scheduleId'
      preLoaderRoute: typeof GamesGameIdSchedulesScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId/schedules/$scheduleId': {
      id: '/characters/$characterId/schedules/$scheduleId'
      path: '/characters/$characterId/schedules/$scheduleId'
      fullPath: '/characters/$characterId/schedules/$scheduleId'
      preLoaderRoute: typeof CharactersCharacterIdSchedulesScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/schedules/$scheduleId_/scheduling': {
      id: '/games/$gameId/schedules/$scheduleId_/scheduling'
      path: '/games/$gameId/schedules/$scheduleId/scheduling'
      fullPath: '/games/$gameId/schedules/$scheduleId/scheduling'
      preLoaderRoute: typeof GamesGameIdSchedulesScheduleIdSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  MagicLinkRoute: MagicLinkRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  SignInRoute: SignInRoute,
  Confirm_new_userTokenRoute: Confirm_new_userTokenRoute,
  GamesNewRoute: GamesNewRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  Magic_linkTokenRoute: Magic_linkTokenRoute,
  PasswordResetTokenRoute: PasswordResetTokenRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  InvitationsIndexRoute: InvitationsIndexRoute,
  GamesIdEditRoute: GamesIdEditRoute,
  CharactersIdIndexRoute: CharactersIdIndexRoute,
  GamesIdIndexRoute: GamesIdIndexRoute,
  CharactersCharacterIdSchedulesScheduleIdRoute:
    CharactersCharacterIdSchedulesScheduleIdRoute,
  GamesGameIdSchedulesScheduleIdRoute: GamesGameIdSchedulesScheduleIdRoute,
  CharactersCharacterIdSchedulesIndexRoute:
    CharactersCharacterIdSchedulesIndexRoute,
  GamesGameIdSchedulesIndexRoute: GamesGameIdSchedulesIndexRoute,
  GamesGameIdSchedulesScheduleIdSchedulingRoute:
    GamesGameIdSchedulesScheduleIdSchedulingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
