defmodule GameNight.Repo.Migrations.PartialUniqueIndexForNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:notifications, [:user_id, :subject_type, :subject_id, :kind],
                     name: "notifications_unique_user_subject_kind_index"
                   )

    create unique_index(:notifications, [:user_id, :subject_type, :subject_id, :kind],
             name: "notifications_unique_user_subject_kind_index",
             where: "(kind <> 'schedule_reminder')"
           )
  end

  def down do
    drop_if_exists unique_index(:notifications, [:user_id, :subject_type, :subject_id, :kind],
                     name: "notifications_unique_user_subject_kind_index"
                   )

    create unique_index(:notifications, [:user_id, :subject_type, :subject_id, :kind],
             name: "notifications_unique_user_subject_kind_index"
           )
  end
end
