defmodule GameNight.Repo.Migrations.AddGamesResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:games, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "games_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:games, [:owner_id, :status, :updated_at],
             name: "games_owner_status_updated_at_index"
           )
  end

  def down do
    drop constraint(:games, "games_owner_id_fkey")

    drop_if_exists index(:games, [:owner_id, :status, :updated_at],
                     name: "games_owner_status_updated_at_index"
                   )

    drop table(:games)
  end
end
