defmodule GameNight.Repo.Migrations.CreateInvitePlayersResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:players, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :character_name, :text, null: false
      add :character_summary, :text
      add :gm_notes, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "players_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "players_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:players, [:game_id, :status, :updated_at],
             name: "players_game_status_updated_at_index"
           )

    create index(:players, [:user_id, :status, :updated_at],
             name: "players_user_status_updated_at_index"
           )

    create unique_index(:players, [:game_id, :user_id], name: "players_unique_game_user_index")

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :subject_type, :text, null: false
      add :subject_id, :uuid, null: false
      add :read_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:notifications, [:user_id, :resolved_at, :inserted_at],
             name: "notifications_user_resolved_inserted_index"
           )

    create unique_index(:notifications, [:user_id, :subject_type, :subject_id, :kind],
             name: "notifications_unique_user_subject_kind_index"
           )

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :character_name, :text, null: false
      add :character_summary, :text
      add :gm_notes, :text
      add :status, :text, null: false, default: "pending"
      add :token_jti, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "invitations_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :inviter_id,
          references(:users,
            column: :id,
            name: "invitations_inviter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :accepted_player_id,
          references(:players,
            column: :id,
            name: "invitations_accepted_player_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:invitations, [:email, :status], name: "invitations_email_status_index")

    create index(:invitations, [:game_id, :status, :updated_at],
             name: "invitations_game_status_updated_at_index"
           )

    create unique_index(:invitations, [:game_id, :email],
             name: "invitations_unique_game_email_open_index",
             where: "(status IN ('pending', 'accepted'))"
           )
  end

  def down do
    drop constraint(:invitations, "invitations_game_id_fkey")

    drop constraint(:invitations, "invitations_inviter_id_fkey")

    drop constraint(:invitations, "invitations_accepted_player_id_fkey")

    drop_if_exists unique_index(:invitations, [:game_id, :email],
                     name: "invitations_unique_game_email_open_index"
                   )

    drop_if_exists index(:invitations, [:game_id, :status, :updated_at],
                     name: "invitations_game_status_updated_at_index"
                   )

    drop_if_exists index(:invitations, [:email, :status], name: "invitations_email_status_index")

    drop table(:invitations)

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop_if_exists unique_index(:notifications, [:user_id, :subject_type, :subject_id, :kind],
                     name: "notifications_unique_user_subject_kind_index"
                   )

    drop_if_exists index(:notifications, [:user_id, :resolved_at, :inserted_at],
                     name: "notifications_user_resolved_inserted_index"
                   )

    drop table(:notifications)

    drop constraint(:players, "players_game_id_fkey")

    drop constraint(:players, "players_user_id_fkey")

    drop_if_exists unique_index(:players, [:game_id, :user_id],
                     name: "players_unique_game_user_index"
                   )

    drop_if_exists index(:players, [:user_id, :status, :updated_at],
                     name: "players_user_status_updated_at_index"
                   )

    drop_if_exists index(:players, [:game_id, :status, :updated_at],
                     name: "players_game_status_updated_at_index"
                   )

    drop table(:players)
  end
end
