defmodule GameNight.Repo.Migrations.AddPageMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:page_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :route, :text, null: false
      add :metric_name, :text, null: false
      add :value, :float, null: false
      add :rating, :text, null: false
      add :user_agent, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "page_metrics_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:page_metrics, "page_metrics_user_id_fkey")

    drop table(:page_metrics)
  end
end
