defmodule GameNight.Repo.Migrations.CreateScheduleResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :month, :bigint, null: false
      add :year, :bigint, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :time_zone, :text, null: false
      add :status, :text, null: false, default: "preparing"
      add :posted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "schedules_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:schedules, [:game_id, :year, :month], name: "schedules_game_year_month_index")

    create unique_index(:schedules, [:game_id, :year, :month],
             name: "schedules_unique_per_game_month_index"
           )

    create table(:schedule_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :is_late_join, :boolean, null: false, default: false
      add :np_only, :boolean, null: false, default: false
      add :submitted_at, :utc_datetime_usec

      add :joined_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :schedule_id,
          references(:schedules,
            column: :id,
            name: "schedule_participants_schedule_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :player_id,
          references(:players,
            column: :id,
            name: "schedule_participants_player_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:schedule_participants, [:player_id, :schedule_id],
             name: "schedule_participants_player_schedule_index"
           )

    create index(:schedule_participants, [:schedule_id, :np_only, :submitted_at, :joined_at],
             name: "schedule_participants_roster_index"
           )

    create unique_index(:schedule_participants, [:schedule_id, :player_id],
             name: "schedule_participants_unique_per_schedule_player_index"
           )

    create table(:schedule_days, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day, :bigint, null: false
      add :gm_status, :text, null: false, default: "NA"
      add :final_status, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :schedule_id,
          references(:schedules,
            column: :id,
            name: "schedule_days_schedule_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:schedule_days, [:schedule_id, :day], name: "schedule_days_schedule_day_index")

    create unique_index(:schedule_days, [:schedule_id, :day],
             name: "schedule_days_unique_per_schedule_day_index"
           )

    create table(:participant_days, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day, :bigint, null: false
      add :status, :text, null: false, default: "NA"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :participant_id,
          references(:schedule_participants,
            column: :id,
            name: "participant_days_participant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :schedule_id,
          references(:schedules,
            column: :id,
            name: "participant_days_schedule_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:participant_days, [:participant_id, :day],
             name: "participant_days_participant_day_index"
           )

    create unique_index(:participant_days, [:participant_id, :day],
             name: "participant_days_unique_per_participant_day_index"
           )
  end

  def down do
    drop constraint(:participant_days, "participant_days_participant_id_fkey")

    drop constraint(:participant_days, "participant_days_schedule_id_fkey")

    drop_if_exists unique_index(:participant_days, [:participant_id, :day],
                     name: "participant_days_unique_per_participant_day_index"
                   )

    drop_if_exists index(:participant_days, [:participant_id, :day],
                     name: "participant_days_participant_day_index"
                   )

    drop table(:participant_days)

    drop constraint(:schedule_days, "schedule_days_schedule_id_fkey")

    drop_if_exists unique_index(:schedule_days, [:schedule_id, :day],
                     name: "schedule_days_unique_per_schedule_day_index"
                   )

    drop_if_exists index(:schedule_days, [:schedule_id, :day],
                     name: "schedule_days_schedule_day_index"
                   )

    drop table(:schedule_days)

    drop constraint(:schedule_participants, "schedule_participants_schedule_id_fkey")

    drop constraint(:schedule_participants, "schedule_participants_player_id_fkey")

    drop_if_exists unique_index(:schedule_participants, [:schedule_id, :player_id],
                     name: "schedule_participants_unique_per_schedule_player_index"
                   )

    drop_if_exists index(
                     :schedule_participants,
                     [:schedule_id, :np_only, :submitted_at, :joined_at],
                     name: "schedule_participants_roster_index"
                   )

    drop_if_exists index(:schedule_participants, [:player_id, :schedule_id],
                     name: "schedule_participants_player_schedule_index"
                   )

    drop table(:schedule_participants)

    drop constraint(:schedules, "schedules_game_id_fkey")

    drop_if_exists unique_index(:schedules, [:game_id, :year, :month],
                     name: "schedules_unique_per_game_month_index"
                   )

    drop_if_exists index(:schedules, [:game_id, :year, :month],
                     name: "schedules_game_year_month_index"
                   )

    drop table(:schedules)
  end
end
